menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  Links: /links



## favicon 
favicon: /favicon.ico


## 网站公告设置
notification: |-
            <p>慢慢学，来得及，不要慌
            </p>

## 社交设置
social:
 - name: Github
   icon: '&#xeee2;'
   href: https://github.com/xyhmnb
 - name: 邮箱
   icon: '&#xe69f;'
   href: 1459792120@qq.com
 - name: 微信
   icon: '&#xe7e5;'
   href: 
 - name: 微博
   icon: '&#xe629;'
   href: 没有微博
   
   

# add post views
leancloud_visitors:
  enable: true
  app_id: hESKc51xYeFsVNctLcYmpOS1-gzGzoHsz
  app_key: IPK32hWXJh8WMPOW4xEqsA9V

## 主题评论

### gitment
gitment:
  enable: false
  owner: 
  repo: 
  client_id: 
  client_secret: 
  perPage: 10

### 来必力
livere: 
  enable: false
  livere_uid: 

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 

### Disqus评论
disqus:
  enable: false
  shortname: 
  count: false

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid: cytsbYV5p
  conf: prod_5db6bea920c9a0d149cedeab44860234

# Valine评论
# 需要 https://leancloud.cn 的appid和appkey 
# 更多请登录 https://valine.js.org
valine:
  enable: false
  appid:  hESKc51xYeFsVNctLcYmpOS1-gzGzoHsz  # 你的appid
  appkey: IPK32hWXJh8WMPOW4xEqsA9V  # 你的appkey
  notify: false # 开启评论邮件回复 , https://github.com/xCss/Valine/wiki
  verify: false # 开启验证码
  placeholder: ヾﾉ≧∀≦)o来啊，快活啊! # 评论框显示内容
  avatar: monsterid # gravatar 头像类型
  guest_info: nick,mail,link # 评论者需要填写的属性
  pageSize: 10 # 每页评论数


## 网站访问统计

### 网盟CNZZ统计
cnzz_analytics:

### 百度统计
baidu_analytics: 1d283676d7e81d10054b06f70a90decf

### 谷歌统计
google_analytics: 

### 腾讯分析
tencent_analytics: 

### 百度文章推送
baidu_push:

## ICP备案号:
icp: 豫ICP备10206454号-2

## 开启Hosted by Coding Pages标识
coding_pages: true

## 友链设置

# for links
links:
 - url: http://www.xyhmnb.ml
   name: 友链1
   title: xxx
 - url: http://www.xyhmnb.ml
   name: 友链2
   title: xxx
 - url: http://www.xyhmnb.ml
   name: 友链3
   title: xxx
 - url: http://www.xyhmnb.ml
   name: 友链3
   title: xxx






